steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'europe-west1-docker.pkg.dev/crypto-arcade-460911-q9/mda/kedro-pipeline',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'europe-west1-docker.pkg.dev/crypto-arcade-460911-q9/mda/kedro-pipeline'
    ]
